# Copyright (c) 2026 Seungwon Lee
# SPDX-License-Identifier: MIT
"""PyMOL adapter protocol used by engine core."""

from __future__ import annotations

from typing import Any, Protocol


class PyMOLAdapter(Protocol):
    def get_version(self) -> str: ...

    def get_object_names(self) -> list[str]: ...

    def count_atoms(self, selection: str) -> int: ...

    def load_structure(self, path: str, object_name: str) -> None: ...

    def show_representation(self, representation: str, selection: str) -> None: ...

    def hide_representation(self, representation: str, selection: str) -> None: ...

    def color_selection(self, color: str, selection: str) -> None: ...

    def zoom_selection(self, selection: str, buffer: float) -> None: ...

    def label_residues(self, selection: str) -> None: ...

    def render_png(
        self, path: str, width: int, height: int, dpi: int, ray: bool
    ) -> object | None: ...

    def save_session(self, path: str) -> None: ...

    def restore_session(self, path: str) -> None: ...

    def execute_pml(self, command: str) -> Any: ...

    def clear(self) -> None: ...
